name: django
type: service
from: python
fromVersionConstraint: "^1.1.0"
fromVersion: "1.1.0"
title: Python (Django)
labels:
- django
- python

env:
- name: GUNICORN_APP
  value: myapp.wsgi:application
- name: CELERY_APP
  value: myapp
- name: DJANGO_SECRET_KEY
  value: '{{django_secret_key}}'
  secret: true
- name: DJANGO_DEBUG
  value: 'true'
  envType: dev

links:
- name: db
  env:
  - name: DATABASE_URL
    value: '{{link.database.url}}'
    secret: true
- name: redis
  env:
  - name: CELERY_BROKER_URL
    value: 'redis://:{{link.tokens.password}}@{{link.host}}:{{link.port}}/0'
    secret: true

tokens:
- name: django_secret_key
  generate:
    regex: '[0-9a-f]{64}'

derivatives:
- name: django-celery
  icon: celery
  title: Celery
  args: ['celery', 'worker', '--loglevel=INFO']
  type: service
  required: false

build:
  dockerfile: Dockerfile
  connect: true
  boilerplates:
  - name: django
    title: Django boilerplate
    repo: https://github.com/wodby/django-boilerplate
    branch: main

actions:
- name: database_migrate
  title: Run migrate
  args:
  - python
  - manage.py
  - migrate
  type: post_deploy
- name: collect_static
  title: Collect static files
  args:
  - python
  - manage.py
  - collectstatic
  - --no-input
  type: post_deploy

workspace:
  reload: watch
